OpenAIModel:
  model: "gpt-4o-mini"
  api_key: "sk-Y9P2ZYbyYK0HNbjBjj5s6yddubVCZ36WqCbXEVcYXSQMiaEm"

GLMModel:
  model_url: "your_chatglm_model_url"
  timeout: 300

common:
  book: "tests/test.pdf"
  file_format: "markdown"